---
title: "preprocessing"
output: pdf_document
date: "2022-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='hide', message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.height = 4, fig.width = 6)
options(knitr.kable.NA = '',knitr.table.format = "latex")
knitr::read_chunk('../r-imports/init.R')
library(kableExtra)
```

```{r init-setup}
```


---
# ##################################################
# Run this when not knitting (and none of the above)
---

```{r, eval = FALSE}
source('r-imports/init.R')
```

---
# Any collab code below this line :)
# ##################################################
---





```{r}
data_gwp100 = read_excel("data-raw/essd_ghg_data_gwp100.xlsx",sheet = "data")

#data_lulucf = read_excel("data-raw/lulucf.xlsx",sheet = "data")
data_lulucf = read_excel("data-raw/egr22_country_data.xlsx",sheet = "data") %>%
  rename(ISO = iso, co2_lulucf = CO2_LULUCF_NGHGI) %>%
  select(ISO, year, co2_lulucf)

load("data-raw/data_wdi.RData") 
data_wdi %<>%
  select(-country)

data_base = data_gwp100 %>%
  left_join(data_wdi,by=c("ISO","year")) %>%
  left_join(data_lulucf,by=c("ISO","year")) %>%
  mutate(
    GHG_pc = GHG/pop,
    GHG_pg = GHG/gdp_ppp,
    GDP_pc = gdp_ppp/pop
  ) %>%
  filter(year <= 2019) %>% 
  mutate(
    EU = country %in% eurostat::eu_countries[2]$name,
    woc = country != "China",
    deving_woc = woc & region_ar6_dev == "developing",
    deved = region_ar6_dev == "developed",
    adp_region_woc = woc & region_ar6_6 == "Asia and developing Pacific",
    adp_region_deving_woc = adp_region_woc & deving_woc
  ) %>% 
  select(-woc)


save(data_base,file="data-transf/data_base.RData")
```


```{r}

#load("data-raw/data_iea.RData") Thanks to Will we got better Data now. 
#load better energy data 
data_energy<-read_excel("data-raw/data_energy_co2_countries.xlsx",sheet = "data")
# filter for ISO, Year and Energy
data_energy%<>%
  select(ISO,year,energy)

data_kaya = data_base %>% 
  group_by(across(-c(sector_title,subsector_title,N2O, CH4,GHG,co2_lulucf,gdp_ppp, Fgas,GHG_pc,GHG_pg,CO2))) %>% 
  na.omit() %>% 
  summarise(CO2=sum(CO2,na.rm=T))%>%
  left_join(data_energy,by=c("ISO","year")) %>%
  mutate(energy_intensity = energy/GDP_pc) %>%
  mutate(carbon_intensity = CO2/energy) %>%
  na.omit() %>% 
  pivot_longer(c(CO2,pop,GDP_pc,energy_intensity,carbon_intensity),names_to = "var",values_to = "value")





save(data_kaya,file="data-transf/data_kaya.RData")
```


```{r}
load("data-raw/data_cumulative_co2.RData")

# need to add filling values when joining
dev_status=data_base %>% 
    group_by(country, year,region_ar6_dev) %>% 
    summarise()

data_hist_co2=data_cumulative_co2 %>% 
  left_join(dev_status, by= c("country","year")) %>% 
  filter(year <= 2019) %>% 
    mutate(
      EU = country %in% eurostat::eu_countries[2]$name,
      woc = country != "China",
      deving_woc = woc & region_ar6_dev == "developing",
      deved = region_ar6_dev == "developed",
      adp_region_woc = woc & region_ar6_6 == "Asia and developing Pacific",
      adp_region_deving_woc = adp_region_woc & deving_woc
    ) %>% 
  select(-woc)



save(data_hist_co2,file="data-transf/data_hist_co2.RData")
```