---
title: "analysis"
output: pdf_document
date: "2022-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='hide', message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.height = 4, fig.width = 6)
options(knitr.kable.NA = '',knitr.table.format = "latex")
knitr::read_chunk('../r-imports/init.R')
library(kableExtra)
```

```{r init-setup}
```


---
# ##################################################
# Run this when not knitting (and none of the above)
---

```{r, eval = FALSE}
source('r-imports/init.R')
```

---
# Any collab code below this line :)
# ##################################################
---


```{r load data}
load("data-transf/data_base.RData")

#load("data-raw/data_kaya.RData")



```


```{r overview statistics: emissions per capita development 1970:2020}

#summarize per capita emissions by country
data_countries <- data_base %>% 
  group_by(country,year,region_ar6_6,pop) %>% 
  summarise(GHG_pc=sum(GHG_pc,na.rm=TRUE))  
   

#to show chinas development in rleations to diffrent world regions

data_regions <- data_countries %>%
  mutate(pop=replace_na(pop,0)) %>% # check if zero transformation changes statitstics
  group_by(region_ar6_6,year) %>% 
  summarise(GHG_pc=weighted.mean(GHG_pc,pop,na.rm=TRUE)) %>% 
  rename(region = region_ar6_6) %>% 
  filter(region %ni% c("Intl. Aviation", "Intl. Shipping"))



# combining data frames

china_and_regions <- rbind(data_regions, data_china)




glimpse(china_and_regions)
# plotting

china_and_regions %>% 
  ggplot(.,aes(y=GHG_pc,fill=as.factor(region), x=year)) +
  geom_line(color="#636363",alpha=0.3) +
  theme_ghg()
  
  
ggplot(china_and_regions,aes(x=year,y=GHG_pc,fill=region)) +
  geom_area(color="#636363") +              ## Define a colour (grey) to outline each area 
  ylab("Total GHG emissions (GtCO2eq)") +   ## replace the label on the y axis
  theme_bw() +                              ## Use my favourite "black/white" theme 
  scale_fill_brewer(palette="Set2") +       ## Use my favourite color scale from https://colorbrewer2.org
  theme(axis.title.x = element_blank()) +   ## Remove the x axis label (years is obvious)
  ggtitle("Total anthropogenic GHG emissions continue to grow")  
  
  
  #ggplot(.,aes(x=GHG_pc,y=,fill=Region)) +
  #  geom_density_ridges(color="#636363",alpha=0.5) +
  #  scale_fill_brewer(palette="Set2") +
  #  theme_bw() +
   # xlab("GHG emissions per capita (tCO2eq/capita)") +
  #  ggtitle("Distribution of emissions by country and region") + 
  #  theme(legend.position="none",
  #        axis.title.y = element_blank())


  

```


```{r overview statistics: emissions by sector development 1970:2020 }
data_countries <- data_ghg %>% 
  group_by(ISO,country,year,sector) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))



```


```{r overview statistics: emissions by Gas development 1970:2020 }
plot_data_gases <- data_ghg %>%       # create a new variable called "data_gases", copied from "data_ghg"
  group_by(year) %>%                  # choose "years" as our grouping variable
  summarise(CO2=sum(CO2,na.rm=TRUE),  # sum up the CO2 column by years, ignoring any missing values
            CH4=sum(CH4,na.rm=TRUE),  # sum up the CH4 column by years, ...
            N2O=sum(N2O,na.rm=TRUE),  # etc.
            Fgas=sum(Fgas,na.rm=TRUE))

```


```{r overview statistics: emissions changes }
data_change <- data_ghg %>% 
  group_by(ISO,country,region_ar6_6,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))


## in this next chunk I calculate 3 different types of changes for the time period 2010-2019

data_change <- data_change %>% 
  filter(year %in% c(2010,2019)) %>% 
  group_by(ISO,country) %>% 
  mutate(change_abs = last(GHG)-first(GHG),               ## absolute change, or the difference in emissions between t2 and t1
         change_rel = change_abs/first(GHG),              ## relative change, or the ratio of absolute change to emissions in t1
         change_avg_annual = ((last(GHG)/first(GHG))^(1/(2019-2010))-1)) ## average annual change using the CGAR formula


```

```{r overview statistics: Kaya decomposition }
data_kaya <- data_kaya %>% 
  na.omit()

## now simply calculate the kaya identity (we already have CO2 and population)

data_kaya <- data_kaya %>% 
  mutate(GDP_pc = gdp_ppp/pop) %>% 
  mutate(energy_intensity = energy/gdp_ppp) %>% 
  mutate(carbon_intensity = CO2/energy)
```