---
title: "data import"
output: pdf_document
date: "2022-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='hide', message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.height = 4, fig.width = 6)
options(knitr.kable.NA = '',knitr.table.format = "latex")
knitr::read_chunk('../r-imports/init.R')
library(kableExtra)
```

```{r init-setup}
```


---
# ##################################################
# Run this when not knitting (and none of the above)
---

```{r, eval = FALSE}
source('r-imports/init.R')
```


---
# Any collab code below this line :)
# ##################################################
---





```{r}

download.file("https://zenodo.org/record/6483002/files/essd_ghg_data_gwp100.xlsx?download=1","data-raw/gwp100.xlsx")
download.file("https://zenodo.org/record/7190601/files/LULUCF%20NGHGI%20database%20August%202022.xlsx?download=1","data-raw/lulucf.xlsx")

library(httr)
url = "https://zenodo.org/record/7190601/files/LULUCF%20NGHGI%20database%20August%202022.xlsx?download=1"
GET(url, write_disk("data-raw/lulucf.xlsx", overwrite=TRUE))

```


```{r}

# ### Using the WDI package to call the Worldbank API and download some indicators 

# # gdp at ppp 

wdi_gdp<-WDI(country = "all",indicator = "NY.GDP.MKTP.PP.KD",start = 1970,end = 2019,extra=TRUE,language = "en") %>%
    select(ISO=iso3c, country, year, gdp_ppp=`NY.GDP.MKTP.PP.KD`) %>%
    filter(!is.na(ISO))
# 
# # POP
wdi_pop<-WDI(country = "all",indicator = "SP.POP.TOTL",start = 1970,end = 2019,extra=TRUE,language = "en")%>%
    select(ISO=iso3c, country, year, pop=`SP.POP.TOTL`) %>%
    filter(!is.na(ISO))

data_wdi <- left_join(wdi_pop,wdi_gdp,by=c("ISO","year","country"))
data_wdi <- data_wdi %>% 
   arrange(ISO,country,year)
 
   save(data_wdi,file="data-raw/data_wdi.RData")
 
```


```{r}

```